In [1]:
#1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

In [2]:
#NumPy, which stands for Numerical Python, is a foundational library for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. Here’s an overview of its purpose and advantages:

#Purpose of NumPy
#Array Handling: NumPy introduces the ndarray (n-dimensional array) object, which allows for efficient storage and manipulation of large datasets.
#Numerical Computing: It provides functions for performing mathematical operations on arrays, making it easier to perform complex calculations.
#Interoperability: NumPy arrays serve as the basis for many other scientific libraries in Python, such as SciPy, Pandas, and Matplotlib.
#Advantages of NumPy
#Performance:

#Speed: NumPy operations are implemented in C, making them much faster than native Python operations, especially for large datasets.
#Vectorization: NumPy allows for vectorized operations, meaning you can apply operations to entire arrays without the need for explicit loops, leading to cleaner and more efficient code.
#Memory Efficiency:

#NumPy arrays are more memory-efficient than Python lists, as they store data in contiguous memory locations and have a fixed type.
#This can lead to significant savings when handling large datasets.
#Convenient Mathematical Functions:

#NumPy provides a wide range of mathematical functions, such as linear algebra operations, statistical functions, Fourier transforms, and random number generation, making it easy to perform complex analyses.
#Multi-dimensional Data:

#NumPy supports n-dimensional arrays, allowing for the representation of complex datasets in various dimensions, which is particularly useful in fields like physics, engineering, and finance.
#Easy Integration:

#NumPy works seamlessly with other Python libraries and tools, enhancing its usability in scientific computing and data analysis workflows.
#Broadcasting:

#The broadcasting feature allows NumPy to perform operations on arrays of different shapes in a flexible way, simplifying coding and reducing the need for manual reshaping.
#Enhancing Python's Capabilities
#NumPy enhances Python’s numerical capabilities by providing a high-performance environment tailored for numerical computations. With its array-oriented programming style, it allows users to express operations succinctly and efficiently. This leads to:

#Reduced Complexity: Tasks that would require cumbersome loops and conditionals can often be expressed in a single line of NumPy code.
#Increased Productivity: Researchers and data scientists can focus on solving problems rather than optimizing their code for performance.
#Access to Advanced Algorithms: NumPy provides access to advanced algorithms and operations that are optimized for performance, helping users tackle complex scientific and engineering problems.
#In summary, NumPy is a critical tool for scientific computing in Python, providing efficient data structures, powerful numerical capabilities, and a strong foundation for further libraries, ultimately enhancing Python's role in data analysis and numerical operations.





In [3]:
#2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

In [5]:
#In NumPy, both np.mean() and np.average() are used to compute the average of array elements, but they have some key differences in functionality and use cases. Here's a comparison of the two:

#np.mean()
#Purpose: Computes the arithmetic mean of the elements in the array.
#Syntax: np.mean(a, axis=None, dtype=None, out=None)
#Parameters:
#a: Input array.
#axis: Axis or axes along which the means are computed. By default, it computes the mean of the flattened array.
#dtype: Data type of the returned array.
#out: Alternative output array to store the result.
#Behavior: Treats all elements equally and calculates the mean as the sum of all elements divided by the number of elements.
#np.average()
#Purpose: Computes the weighted average of the elements in the array, with the option to specify weights.
#Syntax: np.average(a, axis=None, weights=None, returned=False)
#Parameters:
#a: Input array.
#axis: Axis or axes along which the averages are computed.
#weights: An optional array of weights. If provided, it must be the same shape as a, or it must be broadcastable to a.
#returned: If True, the function returns a tuple containing the average and the sum of the weights.
#Behavior: Calculates the average considering the provided weights. If no weights are specified, it behaves like np.mean().
#Key Differences
#Weights:

#np.mean(): No weighting; treats all elements equally.
#np.average(): Allows for weights, which can emphasize certain elements more than others in the calculation.
#Return Values:

#np.mean(): Always returns a single average value (or an array of averages if computed along an axis).
#np.average(): Can return an additional value (the sum of the weights) if the returned parameter is set to True.
#Use Cases:

#np.mean(): Use when you simply want to compute the average of a dataset without any weighting.
#np.average(): Use when you want to compute a weighted average where some elements contribute more to the final average than others.
#Example Usage
#np.mean():

#code
import numpy as np
data = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(data)  # Returns 3.0
#np.average():

#code
import numpy as np
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 1, 1, 1, 1])  # Equal weights
average_value = np.average(data, weights=weights)  # Also returns 3.0

# With different weights
weights = np.array([1, 2, 3, 4, 5])  # Heavier weighting for higher values
weighted_average = np.average(data, weights=weights)  # Returns 4.0
#Conclusion
#In summary, choose np.mean() when you want a straightforward average of the dataset, and use np.average() when you need to consider different contributions from elements through weighting

In [6]:
#3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In [17]:
#Reversing a NumPy array can be done along different axes using slicing techniques. Here’s how to reverse both 1D and 2D arrays:

#Reversing a 1D Array
#To reverse a 1D array, you can use slicing with the step parameter set to -1.

#Example:

#code
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_arr_1d = arr_1d[::-1]

print("Original 1D array:", arr_1d)
print("Reversed 1D array:", reversed_arr_1d)
#Output:

#code
#Original 1D array: [1 2 3 4 5]
#Reversed 1D array: [5 4 3 2 1]
#Reversing a 2D Array
#For a 2D array, you can reverse along specific axes. You can specify the axis you want to reverse: axis=0 for rows and axis=1 for columns.

#Reverse along Rows (axis=0)
#Example:

#code
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse the array along the rows (axis 0)
reversed_rows = arr_2d[::-1]

print("Original 2D array:\n", arr_2d)
print("Reversed 2D array (rows):\n", reversed_rows)
#Output:

#code
#Original 2D array:
# [[1 2 3]
# [4 5 6]
 #[7 8 9]]
#Reversed 2D array (rows):
 #[[7 8 9]
 #[4 5 6]
 #[1 2 3]]
#Reverse along Columns (axis=1)
#Example:

#code
import numpy as np

# Reverse the array along the columns (axis 1)
reversed_columns = arr_2d[:, ::-1]

print("Reversed 2D array (columns):\n", reversed_columns)
#Output:

#code
#Reversed 2D array (columns):
# [[3 2 1]
 #[6 5 4]
 #[9 8 7]]
#Summary
#For a 1D array, use slicing with [::-1] to reverse the entire array.
#For a 2D array:
#Use [::-1] to reverse along rows (axis 0).
#Use [:, ::-1] to reverse along columns (axis 1).
#These slicing techniques are efficient and leverage NumPy's powerful array manipulation capabilities.


Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]
Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed 2D array (rows):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed 2D array (columns):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [18]:
#4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance

In [20]:
#In NumPy, you can determine the data type of elements in an array using the .dtype attribute. Here’s how to do it, along with a discussion on the importance of data types in memory management and performance.

#Checking Data Types
#Example:

#code
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Determine the data type
data_type = arr.dtype

print("Data type of the array elements:", data_type)
#Output:

#code
#Data type of the array elements: int64
#Importance of Data Types
#Memory Management:

#Efficient Storage: Different data types consume different amounts of memory. For instance, an int32 uses 4 bytes, while an int64 uses 8 bytes. Choosing an appropriate data type can significantly reduce the memory footprint of your arrays, especially when dealing with large datasets.
#Type Casting: You can specify the data type during array creation (e.g., np.array([1, 2, 3], dtype=np.float32)), which helps in managing memory more effectively.
#Performance:

#Speed of Operations: NumPy operations are optimized for specific data types. For example, operations on arrays of float32 may be faster than on float64, especially on systems with limited processing power or memory bandwidth.
#Vectorization: NumPy’s performance benefits from vectorized operations, which can be more efficient with certain data types. Using appropriate data types can leverage the underlying optimized libraries that NumPy relies on, such as BLAS or LAPACK.
#Compatibility and Interoperability:

#Interfacing with Other Libraries: Many scientific libraries expect specific data types. Using the correct data types ensures compatibility and prevents potential issues when passing data between libraries (e.g., passing NumPy arrays to a machine learning library).
#Avoiding Errors:

#Preventing Data Loss: Using inappropriate data types can lead to issues like overflow (e.g., when using int8 for large numbers) or loss of precision (e.g., using float32 for calculations requiring high precision).
#Debugging and Maintenance: Being aware of data types can help avoid bugs related to unintended type conversions or comparisons, making the code easier to debug and maintain.
#Conclusion
#In summary, understanding and managing data types in NumPy is crucial for optimizing memory usage, enhancing performance, ensuring compatibility with other libraries, and preventing potential errors. The .dtype attribute is a simple yet powerful way to inspect the data type of array elements, allowing for better data management in scientific computing and data analysis tasks.

Data type of the array elements: int64


In [21]:
#5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [22]:
#In NumPy, an ndarray (n-dimensional array) is a powerful data structure used for storing and manipulating large datasets. Here’s an overview of its key features and how it differs from standard Python lists:

#Key Features of ndarray
#Multi-dimensional:

#ndarray can represent arrays of any number of dimensions (1D, 2D, 3D, etc.). This flexibility allows for complex data structures, such as matrices and tensors.
#Homogeneous Data:

#All elements in a NumPy array must be of the same data type. This uniformity leads to more efficient storage and faster processing compared to Python lists, which can hold mixed data types.
#Contiguous Memory Allocation:

#ndarray objects are stored in contiguous blocks of memory, which improves cache locality and access speed. This contrasts with Python lists, which store references to objects in non-contiguous memory locations.
#Performance:

#NumPy operations on ndarray are optimized and typically implemented in C. This results in faster computations, especially for large datasets, due to vectorized operations that allow for bulk processing without explicit loops.
#Broadcasting:

#NumPy supports broadcasting, which allows operations on arrays of different shapes. This feature enables arithmetic operations without needing to manually align shapes, making it easier to work with multi-dimensional data.
#Rich Functionality:

#NumPy provides a vast array of mathematical and statistical functions that can be applied directly to ndarray objects, facilitating complex computations with minimal code.
#Slicing and Indexing:

#Slicing in ndarray is more powerful than in Python lists, allowing for multi-dimensional slicing and advanced indexing techniques (e.g., boolean indexing).
#Reshaping and Size Manipulation:

#You can easily reshape or resize ndarray objects without copying the data, allowing for flexible manipulation of the array dimensions.
#Differences from Standard Python Lists
#Data Type:

#ndarray: Homogeneous; all elements are of the same data type.
#Python Lists: Heterogeneous; can contain elements of different data types.
#Performance:

#ndarray: Faster for numerical operations due to optimized C implementations and contiguous memory layout.
#Python Lists: Slower for numerical operations, especially with large datasets, because they involve Python object overhead and non-contiguous memory.
#Memory Usage:

#ndarray: More memory-efficient for large datasets, as it uses fixed data types and contiguous memory allocation.
#Python Lists: Less memory-efficient, as each element is a reference to a Python object and can lead to more overhead.
#Functionality:

#ndarray: Comes with extensive mathematical and statistical functions built into NumPy, making it suitable for scientific computing.
#Python Lists: Basic functionality and require loops for most mathematical operations, which can be cumbersome.
#Slicing Behavior:

#ndarray: Supports advanced slicing, broadcasting, and multi-dimensional indexing.
#Python Lists: Supports basic slicing but lacks the advanced features of NumPy arrays.
#Conclusion
#ndarray is a cornerstone of NumPy and provides powerful capabilities for handling and manipulating numerical data. Its features make it vastly superior for scientific computing and data analysis compared to standard Python lists, especially when working with large datasets and performing complex calculations.

In [23]:
#6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

In [24]:
#NumPy arrays offer significant performance benefits over Python lists, especially when it comes to large-scale numerical operations. Here are the key areas where NumPy excels:

#1. Memory Efficiency
#Contiguous Memory Allocation: NumPy arrays are stored in contiguous blocks of memory, which allows for better cache performance. This reduces memory access times compared to Python lists, where elements can be scattered across memory.
#Fixed Data Types: NumPy arrays require that all elements be of the same data type. This uniformity reduces overhead and enables more compact storage compared to Python lists, which store references to objects that can have different types.
#2. Performance Speed
#Vectorization: NumPy utilizes vectorized operations, allowing you to apply operations on entire arrays without using explicit loops. This is implemented in optimized C code, which is significantly faster than Python’s interpreted loops.

#Example:

#code
import numpy as np
arr = np.arange(1, 1000000)
result = arr * 2  # Vectorized operation
#Batch Processing: NumPy functions are designed to work with entire arrays, taking advantage of low-level optimizations that are not available with Python lists. This reduces the overhead of Python's for-loop and improves execution speed.

#3. Numerical Stability and Precision
#Optimized Libraries: NumPy relies on highly optimized libraries (like BLAS and LAPACK) for linear algebra and mathematical operations, which can handle large-scale computations more efficiently and accurately compared to manual implementations with lists.
#Data Type Control: NumPy allows for explicit data type specification (e.g., float32, float64), enabling better control over precision and performance in calculations. This is especially crucial for large datasets where numerical precision can be a concern.
#4. Broadcasting
#Flexible Operations: NumPy’s broadcasting feature allows operations on arrays of different shapes without the need for explicit reshaping. This simplifies code and enhances performance by avoiding unnecessary data copying.

#Example:

#code
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])
result = a + b  # Broadcasting adds b to each row of a
#5. Functionality and Convenience
#Rich Set of Functions: NumPy provides a vast array of built-in functions for mathematical and statistical operations, all optimized for performance. This means you can perform complex operations efficiently without having to implement them from scratch.
#Easy Integration with Other Libraries: Many scientific libraries (e.g., SciPy, Pandas, Matplotlib) are built on top of NumPy, enabling seamless and efficient operations across different types of data processing tasks.
#6. Parallelization and Hardware Acceleration
#Support for Parallel Computing: NumPy can leverage multi-threading and parallel computation capabilities of underlying libraries, allowing for better utilization of CPU resources compared to Python lists, which typically operate in a single-threaded manner.
#Conclusion
#In summary, the performance benefits of NumPy arrays over Python lists for large-scale numerical operations are substantial. With improved memory efficiency, faster execution through vectorization, enhanced numerical stability, and a rich set of functionalities, NumPy is the go-to library for scientific computing and data analysis in Python. It significantly reduces computation time and resource usage, making it essential for handling large datasets effectively.


In [25]:
#7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

In [37]:
#In NumPy, vstack() and hstack() are functions used to stack arrays vertically and horizontally, respectively. Here's a comparison of the two along with examples demonstrating their usage.

#vstack()
#Function: numpy.vstack(tup)
#Description: Stacks arrays in sequence vertically (row-wise). The input arrays must have the same shape along all but the first axis.
#Example of vstack()
#code
#import numpy as np

# Creating two 1D arrays
#a = np.array([1, 2, 3])
#b = np.array([4, 5, 6])

# Using vstack
#vstack_result = np.vstack((a, b))
#print("vstack result:")
#print(vstack_result)
#Output:

#code
#vstack result:
#[[1 2 3]
 #[4 5 6]]
#hstack()
#Function: numpy.hstack(tup)
#Description: Stacks arrays in sequence horizontally (column-wise). The input arrays must have the same shape along all but the second axis.
#3Example of hstack()
#code
#import numpy as np

# Creating two 1D arrays
#a = np.array([1, 2, 3])
#b = np.array([4, 5, 6])

# Using hstack
#hstack_result = np.hstack((a, b))
#print("hstack result:")
#print(hstack_result)
#Output:

#code
#hstack result:
#[1 2 3 4 5 6]
#Summary
#vstack() combines arrays vertically, resulting in a new 2D array where the input arrays become rows.
#hstack() combines arrays horizontally, resulting in a new 1D array where the input arrays are concatenated side by side.
#Additional Example with 2D Arrays
#code
# Creating two 2D arrays
#A = np.array([[1, 2], [3, 4]])
#B = np.array([[5, 6], [7, 8]])

# Using vstack
#vstack_2D_result = np.vstack((A, B))
#print("vstack 2D result:")
#print(vstack_2D_result)

# Using hstack
#hstack_2D_result = np.hstack((A, B))
#print("hstack 2D result:")
#print(hstack_2D_result)
#Output:

#code
#vstack 2D result:
#[[1 2]
#[5 6]
# [7 8]]

#hstack 2D result:
#[[1 2 5 6]
 #[3 4 7 8]]
#In this example, vstack() combines the rows of both matrices, while hstack() combines their columns.


In [38]:
#8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions

In [39]:
#In NumPy, fliplr() and flipud() are two functions used to flip arrays, but they operate along different axes.

#fliplr()
#Functionality: Flips an array left to right.
#Axis: It operates along the horizontal axis (axis 1).
#Effect on Dimensions:
#2D Arrays: For a 2D array (matrix), it reverses the order of columns.
#code
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
flipped = np.fliplr(arr)
# Result:
# [[3, 2, 1],
#  [6, 5, 4]]
#1D Arrays: Not applicable, as it requires at least a 2D array.
#3D Arrays: Flips each 2D slice along the last axis.
#code
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
flipped_3d = np.fliplr(arr_3d)
# Result:
# [[[2, 1], [4, 3]],
#  [[6, 5], [8, 7]]]
#flipud()
#Functionality: Flips an array upside down.
#Axis: It operates along the vertical axis (axis 0).
#Effect on Dimensions:
#2D Arrays: For a 2D array, it reverses the order of rows.
#code
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
flipped = np.flipud(arr)
# Result:
# [[4, 5, 6],
#  [1, 2, 3]]
#1D Arrays: Flipping a 1D array behaves like reversing the array.
#code
arr_1d = np.array([1, 2, 3, 4])
flipped_1d = np.flipud(arr_1d)
# Result:
# [4, 3, 2, 1]
#3D Arrays: Flips each 2D slice along the first axis.
#code
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
flipped_3d = np.flipud(arr_3d)
# Result:
# [[[5, 6], [7, 8]],
#  [[1, 2], [3, 4]]]
#Summary
#fliplr(): Flips arrays horizontally (left to right) along axis 1.
#flipud(): Flips arrays vertically (upside down) along axis 0.
#Both functions are useful for manipulating the orientation of arrays depending on the desired layout for analysis or visualization.

In [40]:
9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Object `splits` not found.


In [41]:
#The array_split() function in NumPy is used to split an array into multiple sub-arrays. It's a flexible function that allows you to specify the number of splits, and it can handle cases where the array cannot be evenly divided.

#Functionality of array_split()
#Basic Syntax:

#code
#numpy.array_split(ary, indices_or_sections, axis=0)
#Parameters:

#ary: The input array to be split.
#indices_or_sections: This can be either an integer specifying the number of equal parts to split the array into, or an array of indices at which to split the array.
#axis: The axis along which to split the array. The default is 0 (the first axis).
#Returns: A list of sub-arrays.

#Handling Uneven Splits
#When the total size of the array along the specified axis is not evenly divisible by the number of splits requested, array_split() will handle this gracefully:

#Uneven Division: If the number of elements in the array cannot be evenly divided, the resulting sub-arrays will be of uneven sizes. The first few sub-arrays will contain one more element than the others to account for the remainder.

#For example:

#code
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
split_arr = np.array_split(arr, 3)
# Result:
# [array([1, 2]), array([3, 4]), array([5])]
#Here, arr has 5 elements, and when splitting into 3 parts, the first two parts get 2 elements each, and the last part gets the remaining element.

#Summary of Behavior
#Equal Splits: If the array can be evenly divided, each sub-array will have the same size.
#Uneven Splits: If the array cannot be evenly divided, the extra elements are distributed among the first few sub-arrays, making them larger by one element.
#Flexibility: You can also specify split indices instead of the number of splits, allowing for more customized partitioning.
#This functionality makes array_split() a powerful tool for dividing arrays in data processing, especially when the exact size of the resulting arrays may vary.

In [42]:
#10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations.

In [43]:
#Vectorization and broadcasting are two powerful concepts in NumPy that significantly enhance the efficiency of array operations.

#Vectorization
#Definition: Vectorization refers to the ability to perform operations on entire arrays rather than using explicit loops to process individual elements. This takes advantage of low-level optimizations in NumPy, allowing for faster computations.

#Benefits:

#Performance: Vectorized operations are generally faster than their loop-based counterparts because they are implemented in C and optimized for performance.
#Code Simplicity: Using vectorized operations leads to cleaner, more readable code. Instead of writing nested loops, you can apply operations directly on arrays.
#Example:

#code
import numpy as np

# Without vectorization (using a loop)
arr = np.array([1, 2, 3, 4, 5])
result = []
for x in arr:
    result.append(x ** 2)
# result: [1, 4, 9, 16, 25]

# With vectorization
result_vectorized = arr ** 2
# result_vectorized: array([ 1,  4,  9, 16, 25])
#Broadcasting
#Definition: Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. When the shapes of the arrays are not the same, NumPy automatically adjusts them to make them compatible for element-wise operations.

#How it Works:

#Rules: Broadcasting follows certain rules:
#If the arrays have a different number of dimensions, the smaller-dimensional array is "padded" with ones on the left until they match.
#If the dimensions of the arrays are different, NumPy compares them element-wise. If they are not the same size, one of them must be 1 in that dimension for broadcasting to occur.
#Example:

#code
#import numpy as np

# Arrays of different shapes
a = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
b = np.array([10, 20, 30])             # Shape (3,)

# Broadcasting in action
result_broadcasted = a + b
# result_broadcasted:
# [[11, 22, 33],
#  [14, 25, 36]]
#In this case, b is effectively treated as if it were [[10, 20, 30], [10, 20, 30]] for the purpose of the addition.

#Contributions to Efficient Array Operations
#Reduced Computation Time: By leveraging vectorization, NumPy avoids the overhead of Python loops, resulting in faster execution of array operations.
#Memory Efficiency: Broadcasting enables operations without needing to create copies of arrays, which can save memory.
#Simplified Code: Both vectorization and broadcasting lead to more concise code, making it easier to understand and maintain.
#In summary, vectorization and broadcasting are fundamental to NumPy's design, allowing for efficient, concise, and fast array operations that are essential for numerical computing and data analysis.

In [44]:
#Practical Questions:

In [46]:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [47]:
#You can create a 3x3 NumPy array with random integers between 1 and 100 and then interchange its rows and columns using the following code:

#code
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)

# Interchange rows and columns (transpose the array)
transposed_array = array.T
print("\nTransposed Array:")
print(transposed_array)
#In this code:

#We use np.random.randint(1, 101, size=(3, 3)) to generate the random integers.
#We then use the .T attribute to transpose the array, effectively interchanging its rows and columns.



#You said:
#1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns
#ChatGPT said:
#ChatGPT
#Here's how you can create a 3x3 NumPy array with random integers between 1 and 100, and then interchange its rows and columns:

#code
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)

# Interchange rows and columns (transpose the array)
transposed_array = array.T
print("\nTransposed Array:")
print(transposed_array)
#Explanation:
#Creating the Array: np.random.randint(1, 101, size=(3, 3)) generates a 3x3 array with random integers from 1 to 100.
#Transposing the Array: The .T attribute transposes the array, swapping its rows and columns.
#You can run this code in a Python environment with NumPy installed to see the results!

Original Array:
[[13 73 82]
 [66 84 22]
 [72 22 70]]

Transposed Array:
[[13 66 72]
 [73 84 22]
 [82 22 70]]
Original Array:
[[47 11 74]
 [ 2 11 61]
 [22 86 80]]

Transposed Array:
[[47  2 22]
 [11 11 86]
 [74 61 80]]


In [48]:
#2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [49]:
#Here’s how you can generate a 1D NumPy array with 10 elements, reshape it into a 2x5 array, and then into a 5x2 array:

#code
import numpy as np

# Generate a 1D array with 10 elements
array_1d = np.arange(10)  # Creates an array with elements from 0 to 9
print("1D Array:")
print(array_1d)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped into 2x5 Array:")
print(array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped into 5x2 Array:")
print(array_5x2)
#Output Explanation:
#1D Array: The np.arange(10) function creates an array like this:

#code
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
#2x5 Array: The first reshape produces a 2x5 array:

#lua
#code
[[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9]]
#5x2 Array: The second reshape gives a 5x2 array:

#css
#code
[[0, 1],
 [2, 3],
 [4, 5],
 [6, 7],
 [8, 9]]
#You can run this code to see the results!

1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


[[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]]

In [50]:
#3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [51]:
#You can create a 4x4 NumPy array with random float values and then add a border of zeros around it to result in a 6x6 array. Here’s how you can do that:

#code
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros around the array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Border of Zeros:")
print(array_with_border)
#Explanation:
#Creating the Array: np.random.rand(4, 4) generates a 4x4 array with random float values between 0 and 1.
#Adding a Border: np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0) adds a border of zeros around the original array, resulting in a 6x6 array.
#You can run this code to see the output!

Original 4x4 Array:
[[0.89532377 0.93892269 0.00310881 0.78261568]
 [0.09794675 0.08129755 0.8058212  0.62301464]
 [0.43197566 0.88507799 0.39434927 0.99036159]
 [0.21697105 0.42058675 0.79767672 0.39299555]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.89532377 0.93892269 0.00310881 0.78261568 0.        ]
 [0.         0.09794675 0.08129755 0.8058212  0.62301464 0.        ]
 [0.         0.43197566 0.88507799 0.39434927 0.99036159 0.        ]
 [0.         0.21697105 0.42058675 0.79767672 0.39299555 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [52]:
#4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [56]:
#You can create an array of integers from 10 to 60 with a step of 5 using NumPy's arange function. Here’s how you can do that:

#code
#import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
print("Array from 10 to 60 with a step of 5:")
print(array)
#Explanation:
#np.arange(10, 61, 5) generates an array starting from 10 up to (but not including) 61, with increments of 5.
#You can run this code to see the output, which will be:

#code
#Array from 10 to 60 with a step of 5:
#[10 15 20 25 30 35 40 45 50 55 60]

Array from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [57]:
#5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element

In [60]:
#You can create a NumPy array of strings and apply various case transformations using NumPy's vectorized string operations. Here’s how to do it:

#code
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
upper_case = np.char.upper(arr)          # Uppercase
lower_case = np.char.lower(arr)          # Lowercase
title_case = np.char.title(arr)          # Title case
capitalize_case = np.char.capitalize(arr) # Capitalized case

# Display the results
print("Original Array: ", arr)
print("Uppercase: ", upper_case)
print("Lowercase: ", lower_case)
print("Title Case: ", title_case)
print("Capitalized: ", capitalize_case)
#Output:
#less
#code
#Original Array:  ['python' 'numpy' 'pandas']
Uppercase:  ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:  ['python' 'numpy' 'pandas']
#Title Case:  ['Python' 'Numpy' 'Pandas']
Capitalized:  ['Python' 'Numpy' 'Pandas']
#This code demonstrates how to create an array of strings and perform different case transformations using NumPy's string functions.


Original Array:  ['python' 'numpy' 'pandas']
Uppercase:  ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase:  ['python' 'numpy' 'pandas']
Title Case:  ['Python' 'Numpy' 'Pandas']
Capitalized:  ['Python' 'Numpy' 'Pandas']


In [61]:
#6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [64]:
#You can generate a NumPy array of words and insert a space between each character of every word using NumPy's string operations. Here’s how you can do it:

#code
import numpy as np

# Create a NumPy array of words
words = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

# Display the results
print("Original Array: ", words)
print("Spaced Words: ", spaced_words)
#Output:
#code
#Original Array:  ['python' 'numpy' 'pandas']
#Spaced Words:  ['p y t h o n' 'n u m p y' 'p a n d a s']
#This code creates an array of words and uses the np.char.join function to insert spaces between the characters of each word.


Original Array:  ['python' 'numpy' 'pandas']
Spaced Words:  ['p y t h o n' 'n u m p y' 'p a n d a s']


In [65]:
#7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division

In [68]:
#You can create two 2D NumPy arrays and perform element-wise operations such as addition, subtraction, multiplication, and division quite easily. Here’s how to do it:

#code
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Perform element-wise operations
addition = array1 + array2            # Element-wise addition
subtraction = array1 - array2         # Element-wise subtraction
multiplication = array1 * array2      # Element-wise multiplication
division = array1 / array2            # Element-wise division

# Display the results
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)
#Output:
#lua
#code
#Array 1:
#[4 5 6]]
#Array 2:
# [[ 7  8  9]
 #[10 11 12]]
#Addition:
 #[[ 8 10 12]
 #[14 16 18]]
#Subtraction:
 #[[-6 -6 -6]
 #[-6 -6 -6]]
#Multiplication:
# [[ 7 16 27]
# [40 55 72]]
#Division:
# [[0.14285714 0.25       0.33333333]
# [0.4        0.45454545 0.5       ]]
#This code creates two 2D arrays and performs element-wise addition, subtraction, multiplication, and division, displaying the results for each operation.

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [69]:
#8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements

In [70]:
#You can easily create a 5x5 identity matrix using NumPy and extract its diagonal elements. Here’s how you can do it:

#code
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)

print("Identity Matrix:")
print(identity_matrix)
print("Diagonal Elements:")
print(diagonal_elements)
#When you run this code, you'll see the identity matrix and its diagonal elements (which will be [1, 1, 1, 1, 1]). Let me know if you need further assistance!

Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements:
[1. 1. 1. 1. 1.]


In [71]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array

In [72]:
#You can generate an array of 100 random integers between 0 and 1000 and then find all prime numbers in that array using NumPy. Here’s how you can do it:

#code
import numpy as np

# Generate an array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("Random Integers:")
print(random_integers)
print("Prime Numbers:")
print(prime_numbers)
#Explanation:
#Generating Random Integers: The np.random.randint function generates 100 random integers in the specified range.
#Prime Check Function: The is_prime function checks if a number is prime.
#Filtering Primes: A list comprehension is used to create a list of prime numbers from the random integers.
#Run this code to see the random integers and the extracted prime numbers! Let me know if you need anything else.





Random Integers:
[526 557  18 888 940 845 333 736 818 716 608 387 135 533 739 272 912 884
 336 418 397 504 678  16 276 333 169 519 165 902 438 122 567 929 825 197
 733 275  16 778 197  48 486 732 530 127 516 126 936 365 245 331  71 564
 819 815 224 349 559 584 646 159 466 291 814 208 312 899 613  27 487 158
 421 205 826 170  57 342 194 482 853 740 697 906 725 148 967 362 362 516
 774 375 816 145 470  71  90 798 443 991]
Prime Numbers:
[557, 739, 397, 929, 197, 733, 197, 127, 331, 71, 349, 613, 487, 421, 853, 967, 71, 443, 991]


In [73]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [76]:
#You can create a NumPy array to represent daily temperatures for a month (30 days) and then calculate the weekly averages. Here’s how you can do it:

#code
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# For this example, we'll generate random temperatures between 15 and 30 degrees Celsius
daily_temperatures = np.random.uniform(15, 30, size=30)

# Calculate the weekly averages
# We will reshape the array to (4 weeks, 7 days) and calculate the mean for each week
#weekly_averages = daily_temperatures.reshape(4, 7).mean(axis=1)

print("Daily Temperatures for the Month:")
print(daily_temperatures)
print("\nWeekly Averages:")
#print(weekly_averages)
#Explanation:
#Generating Daily Temperatures: The np.random.uniform function generates random temperatures between 15 and 30 degrees Celsius for 30 days.
#Reshaping the Array: The reshape function changes the shape of the array to 4 rows (weeks) and 7 columns (days).
#Calculating Weekly Averages: The mean function calculates the average for each week along the specified axis.
#Run this code, and you'll see the daily temperatures along with the calculated weekly averages! Let me know if you need further help.

Daily Temperatures for the Month:
[20.59918779 21.93145853 26.96484146 24.56558298 29.36342489 20.29258874
 25.96807803 15.17621529 21.72326439 15.92822288 21.47835608 28.90824471
 27.68715421 26.76767747 29.84982336 23.58187157 26.33131729 26.09885242
 24.33578697 22.93483859 16.04284899 20.50004634 28.27942692 23.83192311
 16.8994106  20.91152788 17.23033661 24.82449451 27.35140284 20.9686104 ]

Weekly Averages:
